version: '3'

networks:
    web:
        driver: bridge

services:
    php56:
        container_name: php56
        build: 
            context: ./php56
            args: 
                - NORMAL_GROUP=${NORMAL_GROUP}
                - NORMAL_USER=${NORMAL_USER}
        expose:
            - "9000"
        volumes:
            - ${APP_CODE_PATH}:${CONTAINER_CODE_PATH}:cached
            - ./php56/php-ini-overrides.ini:/etc/php/5.6/fpm/conf.d/99-overrides.ini
            - ${PHP56_LOG_PATH}:/var/log/php56
        environment:
            - TIMEZONE=${TIMEZONE}
        networks:
            - web
    php73:
        container_name: php73
        build: 
            context: ./php73
            args:
                - NORMAL_USER=${NORMAL_GROUP}
                - NORMAL_GROUP=${NORMAL_USER}
        expose:
            - "9000"
        volumes:
            - ${APP_CODE_PATH}:${CONTAINER_CODE_PATH}:cached
            - ./php73/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
            - ${PHP73_LOG_PATH}:/var/log/php73
        networks:
            - web
    php82:
        container_name: php82
        build: 
            context: ./php82
            args: 
                - NORMAL_GROUP=${NORMAL_GROUP}
                - NORMAL_USER=${NORMAL_USER}
        expose:
            - "9000"
        volumes:
            - ${APP_CODE_PATH}:${CONTAINER_CODE_PATH}:cached
            - ./php82/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini    
            - ${PHP82_LOG_PATH}:/var/log/php82
        networks:
            - web    
    nginx:
        container_name: nginx
        build: nginx
        # image: nginx:latest
        volumes:
            - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf:cached
            - ${NGINX_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports: 
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"
        links:
            - php56
            - php73
            - php82
        external_links:
            - "php56:php56"
            - "php73:php73"
            - "php82:php82"
        depends_on:
            - php56
            - php73
            - php82
        networks:
            - web
    mariadb:
        container_name: mariadb
        build: mariadb
        ports:
            - '${MARIADB_PORT}:3306'
        volumes:
            - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
            - ~/data/mariadb:/var/lib/mysql
        environment:
            - TIMEZONE=${TIMEZONE}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - web
    mysql8: 
        container_name: mysql8
        build: mysql8
        ports:
            - "${MYSQL8_PORT}:3306"
        volumes:
            - ./mysql8/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - TIMEZONE=${TIMEZONE}
            - MYSQL_DATABASE=${MYSQL8_DATABASE}
            - MYSQL_USER=${MYSQL8_USER}
            - MYSQL_PASSWORD=${MYSQL8_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL8_ROOT_PASSWORD}
        networks:
            - web
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:            
            - PMA_ARBITRARY=1
            - PMA_VERBOSE=mariadb
            - PMA_HOST=mariadb
            - MYSQL_ROOT_PASSWORD=root
            - PMA_USER=root
            - PMA_PASSWORD=root
        networks:
            - web

