version: '3'

services:
    mariadb:
        container_name: mariadb
        build: mariadb
        # working_dir: /var/www/html
        volumes:
            - ~/data/mariadb:/var/lib/mysql
        environment:
            - TZ=Asia/Taipei
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=default
            - MYSQL_USER=default
            - MYSQL_PASSWORD=secret
        ports:
            - '6608:3306'

    nginx:
        container_name: nginx
        image: 'nginx:alpine'
        working_dir: /var/www/html
        volumes:            
            - /var/www/html:/var/www/html
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './nginx/log:/var/log/nginx'
        ports:
            - '80:80'
    php56:
        container_name: php56
        build: 
            context: ./php56
        # image: 'phpdockerio/php56-fpm'
        working_dir: /var/www/html
        volumes:
            - /var/www/html:/var/www/html
            - ./php56/php-ini-overrides.ini:/etc/php/5.6/fpm/conf.d/99-overrides.ini

    php73:
        container_name: php73
        build: 
            context: ./php73
            args:
                - NORMAL_USER=user
                - NORMAL_GROUP=user
        working_dir: /var/www/html
        volumes:
            - /var/www/html:/var/www/html
            - ./php73/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:            
            - PMA_ARBITRARY=1
            - PMA_VERBOSE=mariadb
            - PMA_HOST=mariadb
            - MYSQL_ROOT_PASSWORD=root
            - PMA_USER=root
            - PMA_PASSWORD=root

